{
 "title": "Systeme",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Utilisation CPU de l'hôte (de 0 à 100%) (sans iowait)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('minute', time) AS time,\n       100 - avg(usage_idle + usage_iowait) AS host_cpu_pct\nFROM cpu\nWHERE cpu = 'cpu-total'\nGROUP BY date_trunc('minute', time)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "CPU Iowait (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('minute', time) AS time,\n       avg(usage_iowait) AS iowait_pct\nFROM cpu\nWHERE cpu = 'cpu-total'\nGROUP BY date_trunc('minute', time)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Utilisation totale du disque (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT used_percent, \"time\" FROM disk "
    }
   ]
  },
  {
   "title": "RAM utilisée (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('minute', \"time\") AS time,\n  100 - avg(available_percent) AS value\nFROM mem\nWHERE \"time\" BETWEEN NOW() - INTERVAL '7 days' AND NOW()\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Utilisation CPU des conteneurs (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time, $__interval),\n  container_name AS \"metric\",\n  AVG(usage_percent) AS \"value\"\nFROM\n  docker_container_cpu\nWHERE\n  $__timeFilter(time)\nGROUP BY 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Utilisation RAM des conteneurs (% max du conteneur)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\", $__interval),\n  container_name,\n  avg(usage_percent)\nFROM docker_container_mem\nWHERE $__timeFilter(\"time\")\nGROUP BY 1,2\nORDER BY 1\n"
    }
   ]
  }
 ]
}