# Configuration globale
[agent]
  interval = "10s"
  round_interval = true

# Input plugin pour les métriques système
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false

[[inputs.mem]]

[[inputs.disk]]

[[inputs.nstat]]

# Input plugin pour les métriques Docker (conteneurs)
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  timeout = "5s"
  docker_label_exclude = ["traefik.*"]

# Sortie vers PostgreSQL
[[outputs.postgresql]]
  connection = "host=postgres user=${TELEGRAF_USER} password=${TELEGRAF_PASSWORD} dbname=${TELEGRAF_DB} sslmode=disable"
